version: '3'

services:
  app:
    image: infracloudio/csvserver:latest
    ports:
      - "9300:9300"
    env_file:
      - csvserver.env
    volumes:
      - ./inputFile:/csvserver/inputdata

  prometheus:
    image: prom/prometheus:v2.45.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

volumes:
  prometheus:
